---
name: Setup catkin
uses: betwo/github-setup-catkin@v1.3.0
description: 'Set up ROS 1 and catkin and add the command-line tools to the PATH.'
author: 'betwo'
jobs:
  catkin-make:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - uses: betwo/github-setup-catkin@master
      with:
        ros-version: 'melodic'
        build-tool: 'catkin_tools'
        workspace: '$GITHUB_WORKSPACE'
    - run: catkin build